# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

# By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.

# https://www.hackerrank.com/contests/microverse-coding-challenges/challenges/euler002

def fibonacci(n)
    arr = []
    arr << 1 if n > 1
    arr << 2 if n > 2
    sum = 0
    while (arr[-1] < n) 
        sum += arr[-1] if arr[-1] % 2 == 0
        arr << arr[-1] + arr[-2]
    end
    return sum
end